from enum import Enum

class TaxaFilters(Enum):

    PLANTCLEF2015_COMMON_SPECIES_LIST = [
        'ABIES ALBA',
        'ABIES CEPHALONICA',
        'ACACIA DEALBATA',
        'ACANTHUS MOLLIS',
        'ACER CAMPESTRE',
        'ACER MONSPESSULANUM',
        'ACER NEGUNDO',
        'ACER OPALUS',
        'ACER PALMATUM',
        'ACER PLATANOIDES',
        'ACER PSEUDOPLATANUS',
        'ACER SACCHARINUM',
        'ACHILLEA FILIPENDULINA',
        'ACHILLEA MILLEFOLIUM',
        'ACHILLEA PTARMICA',
        'ACONITUM LYCOCTONUM',
        'ACONITUM NAPELLUS',
        'ADENOSTYLES ALLIARIAE',
        'ADONIS ANNUA',
        'AEGOPODIUM PODAGRARIA',
        'AESCULUS HIPPOCASTANUM',
        'AETHIONEMA SAXATILE',
        'AGAVE AMERICANA',
        'AGAVE SISALANA',
        'AGRIMONIA EUPATORIA',
        'AGROSTEMMA GITHAGO',
        'AILANTHUS ALTISSIMA',
        'AJUGA CHAMAEPITYS',
        'AJUGA GENEVENSIS',
        'AJUGA IVA',
        'AJUGA REPTANS',
        'ALBIZIA JULIBRISSIN',
        'ALCEA ROSEA',
        'ALLIARIA PETIOLATA',
        'ALLIUM NARCISSIFLORUM',
        'ALLIUM NIGRUM',
        'ALLIUM POLYANTHUM',
        'ALLIUM SCHOENOPRASUM',
        'ALLIUM SPHAEROCEPHALON',
        'ALLIUM TRIQUETRUM',
        'ALLIUM URSINUM',
        'ALNUS ALNOBETULA',
        'ALNUS CORDATA',
        'ALNUS GLUTINOSA',
        'ALTHAEA CANNABINA',
        'ALTHAEA OFFICINALIS',
        'AMARANTHUS DEFLEXUS',
        'AMBROSIA ARTEMISIIFOLIA',
        'AMELANCHIER OVALIS',
        'AMMOPHILA ARENARIA',
        'AMORPHA FRUTICOSA',
        'ANACAMPTIS CHAMPAGNEUXII',
        'ANACAMPTIS LAXIFLORA',
        'ANACAMPTIS MORIO',
        'ANACAMPTIS PYRAMIDALIS',
        'ANACYCLUS CLAVATUS',
        'ANARRHINUM BELLIDIFOLIUM',
        'ANCHUSA ITALICA',
        'ANDROSACE VILLOSA',
        'ANDRYALA INTEGRIFOLIA',
        'ANEMONE ALPINA',
        'ANEMONE CORONARIA',
        'ANEMONE HEPATICA',
        'ANEMONE NEMOROSA',
        'ANEMONE PULSATILLA',
        'ANEMONE RANUNCULOIDES',
        'ANEMONE RUBRA',
        'ANEMONE VERNALIS',
        'ANGELICA HETEROCARPA',
        'ANGELICA SYLVESTRIS',
        'ANTENNARIA DIOICA',
        'ANTHEMIS MARITIMA',
        'ANTHERICUM LILIAGO',
        'ANTHOXANTHUM ODORATUM',
        'ANTHRISCUS SYLVESTRIS',
        'ANTHYLLIS HERMANNIAE',
        'ANTHYLLIS MONTANA',
        'ANTHYLLIS VULNERARIA',
        'ANTIRRHINUM MAJUS',
        'APHYLLANTHES MONSPELIENSIS',
        'AQUILEGIA VULGARIS',
        'ARABIDOPSIS THALIANA',
        'ARBUTUS UNEDO',
        'ARCTIUM LAPPA',
        'ARCTIUM MINUS',
        'ARGYROLOBIUM ZANONII',
        'ARISTOLOCHIA CLEMATITIS',
        'ARISTOLOCHIA PISTOLOCHIA',
        'ARISTOLOCHIA ROTUNDA',
        'ARMERIA ALPINA',
        'ARMERIA ARENARIA',
        'ARMERIA MARITIMA',
        'ARNICA MONTANA',
        'ARTEMISIA VULGARIS',
        'ARUM ITALICUM',
        'ARUM MACULATUM',
        'ARUNDO DONAX',
        'ASPARAGUS ACUTIFOLIUS',
        'ASPARAGUS OFFICINALIS',
        'ASPHODELUS ALBUS',
        'ASPHODELUS CERASIFERUS',
        'ASPHODELUS RAMOSUS',
        'ASPLENIUM ADIANTUM-NIGRUM',
        'ASPLENIUM CETERACH',
        'ASPLENIUM RUTA-MURARIA',
        'ASPLENIUM SCOLOPENDRIUM',
        'ASPLENIUM TRICHOMANES',
        'ASTER ALPINUS',
        'ASTRAGALUS GLYCYPHYLLOS',
        'ASTRAGALUS HAMOSUS',
        'ASTRAGALUS MONSPESSULANUS',
        'ASTRANTIA MAJOR',
        'ASTRANTIA MINOR',
        'ATHYRIUM FILIX-FEMINA',
        'ATRIPLEX PROSTRATA',
        'ATROPA BELLADONNA',
        'AUCUBA JAPONICA',
        'BALLOTA NIGRA',
        'BARBAREA VULGARIS',
        'BARTSIA ALPINA',
        'BARTSIA TRIXAGO',
        'BELLEVALIA ROMANA',
        'BELLIS PERENNIS',
        'BERARDIA LANUGINOSA',
        'BERBERIS JAPONICA',
        'BERBERIS VULGARIS',
        'BERTEROA INCANA',
        'BETA VULGARIS',
        'BETONICA OFFICINALIS',
        'BETULA PENDULA',
        'BETULA PUBESCENS',
        'BETULA UTILIS',
        'BIDENS PILOSA',
        'BISTORTA OFFICINALIS',
        'BITUMINARIA BITUMINOSA',
        'BLACKSTONIA IMPERFOLIATA',
        'BLACKSTONIA PERFOLIATA',
        'BLECHNUM SPICANT',
        'BORAGO OFFICINALIS',
        'BRASSICA NAPUS',
        'BROUSSONETIA PAPYRIFERA',
        'BRYONIA CRETICA',
        'BUDDLEJA DAVIDII',
        'BUGLOSSOIDES PURPUROCAERULEA',
        'BUPLEURUM FRUTICOSUM',
        'BUPLEURUM RANUNCULOIDES',
        'BUXUS SEMPERVIRENS',
        'CAKILE MARITIMA',
        'CALENDULA ARVENSIS',
        'CALENDULA OFFICINALIS',
        'CALLUNA VULGARIS',
        'CALTHA PALUSTRIS',
        'CAMPANULA GLOMERATA',
        'CAMPANULA LATIFOLIA',
        'CAMPANULA MEDIUM',
        'CAMPANULA PATULA',
        'CAMPANULA PERSICIFOLIA',
        'CAMPANULA RAPUNCULUS',
        'CAMPANULA RHOMBOIDALIS',
        'CAMPANULA ROTUNDIFOLIA',
        'CAMPANULA SCHEUCHZERI',
        'CAMPANULA TRACHELIUM',
        'CANNA INDICA',
        'CAPPARIS SPINOSA',
        'CAPSELLA BURSA-PASTORIS',
        'CARDAMINE AMARA',
        'CARDAMINE FLEXUOSA',
        'CARDAMINE HEPTAPHYLLA',
        'CARDAMINE PRATENSIS',
        'CARDUUS ACANTHOIDES',
        'CARDUUS CARLINOIDES',
        'CARDUUS DEFLORATUS',
        'CARDUUS NIGRESCENS',
        'CARDUUS NUTANS',
        'CARDUUS PYCNOCEPHALUS',
        'CAREX FLACCA',
        'CAREX OTRUBAE',
        'CAREX RIPARIA',
        'CARICA PAPAYA',
        'CARLINA ACANTHIFOLIA',
        'CARLINA ACAULIS',
        'CARLINA CORYMBOSA',
        'CARPINUS BETULUS',
        'CARPOBROTUS EDULIS',
        'CARTHAMUS LANATUS',
        'CASTANEA SATIVA',
        'CASUARINA CUNNINGHAMIANA',
        'CATALPA BIGNONIOIDES',
        'CATANANCHE CAERULEA',
        'CEDRUS ATLANTICA',
        'CELTIS AUSTRALIS',
        'CENTAUREA ASPERA',
        'CENTAUREA CALCITRAPA',
        'CENTAUREA CORYMBOSA',
        'CENTAUREA DECIPIENS',
        'CENTAUREA JACEA',
        'CENTAUREA NIGRA',
        'CENTAUREA PANICULATA',
        'CENTAUREA PECTINATA',
        'CENTAUREA SCABIOSA',
        'CENTAURIUM ERYTHRAEA',
        'CENTAURIUM MARITIMUM',
        'CENTELLA ASIATICA',
        'CENTRANTHUS ANGUSTIFOLIUS',
        'CENTRANTHUS RUBER',
        'CEPHALANTHERA LONGIFOLIA',
        'CEPHALANTHERA RUBRA',
        'CEPHALARIA LEUCANTHA',
        'CERASTIUM GLOMERATUM',
        'CERATONIA SILIQUA',
        'CERCIS SILIQUASTRUM',
        'CHAENORRHINUM MINUS',
        'CHAMAEROPS HUMILIS',
        'CHELIDONIUM MAJUS',
        'CHENOPODIUM ALBUM',
        'CHONDRILLA JUNCEA',
        'CICHORIUM INTYBUS',
        'CIRCAEA LUTETIANA',
        'CIRSIUM ACAULON',
        'CIRSIUM ARVENSE',
        'CIRSIUM ERIOPHORUM',
        'CIRSIUM OLERACEUM',
        'CIRSIUM PALUSTRE',
        'CIRSIUM VULGARE',
        'CISTUS ALBIDUS',
        'CISTUS MONSPELIENSIS',
        'CISTUS SALVIIFOLIUS',
        'CITRUS LIMON',
        'CLEMATIS FLAMMULA',
        'CLEMATIS VITALBA',
        'CLINOPODIUM NEPETA',
        'CLINOPODIUM VULGARE',
        'CNEORUM TRICOCCON',
        'COCHLEARIA DANICA',
        'COLCHICUM AUTUMNALE',
        'COLUTEA ARBORESCENS',
        'CONVALLARIA MAJALIS',
        'CONVOLVULUS ALTHAEOIDES',
        'CONVOLVULUS ARVENSIS',
        'CONVOLVULUS CANTABRICA',
        'CONVOLVULUS SEPIUM',
        'CONVOLVULUS SOLDANELLA',
        'CORIARIA MYRTIFOLIA',
        'CORNUS MAS',
        'CORNUS SANGUINEA',
        'CORONILLA GLAUCA',
        'CORONILLA JUNCEA',
        'CORONILLA VALENTINA',
        'CORONILLA VARIA',
        'CORYDALIS SOLIDA',
        'CORYLUS AVELLANA',
        'COTINUS COGGYGRIA',
        'CRATAEGUS AZAROLUS',
        'CRATAEGUS GERMANICA',
        'CRATAEGUS LAEVIGATA',
        'CRATAEGUS MONOGYNA',
        'CREPIS BURSIFOLIA',
        'CREPIS CAPILLARIS',
        'CREPIS FOETIDA',
        'CREPIS SANCTA',
        'CREPIS SETOSA',
        'CRITHMUM MARITIMUM',
        'CROCUS NUDIFLORUS',
        'CRUCIATA LAEVIPES',
        'CUCUMIS SATIVUS',
        'CUPRESSUS SEMPERVIRENS',
        'CYANUS MONTANUS',
        'CYANUS SEGETUM',
        'CYCLAMEN HEDERIFOLIUM',
        'CYDONIA OBLONGA',
        'CYMBALARIA MURALIS',
        'CYNOGLOSSUM CRETICUM',
        'CYPRIPEDIUM CALCEOLUS',
        'CYTISUS LANIGERUS',
        'CYTISUS OROMEDITERRANEUS',
        'CYTISUS SCOPARIUS',
        'DACTYLIS GLOMERATA',
        'DACTYLORHIZA FUCHSII',
        'DACTYLORHIZA INCARNATA',
        'DACTYLORHIZA MACULATA',
        'DACTYLORHIZA MAJALIS',
        'DACTYLORHIZA SAMBUCINA',
        'DAPHNE CNEORUM',
        'DAPHNE GNIDIUM',
        'DAPHNE LAUREOLA',
        'DAPHNE MEZEREUM',
        'DATURA STRAMONIUM',
        'DAUCUS CAROTA',
        'DIANTHUS ARMERIA',
        'DIANTHUS CARTHUSIANORUM',
        'DIANTHUS GALLICUS',
        'DIANTHUS HYSSOPIFOLIUS',
        'DICENTRA SPECTABILIS',
        'DIGITALIS GRANDIFLORA',
        'DIGITALIS LUTEA',
        'DIGITALIS PURPUREA',
        'DIOSCOREA COMMUNIS',
        'DIOSPYROS KAKI',
        'DIPCADI SEROTINUM',
        'DIPHASIASTRUM TRISTACHYUM',
        'DIPLOTAXIS ERUCOIDES',
        'DIPLOTAXIS TENUIFOLIA',
        'DIPSACUS FULLONUM',
        'DITTRICHIA VISCOSA',
        'DORONICUM GRANDIFLORUM',
        'DORYCNIUM HIRSUTUM',
        'DORYCNIUM PENTAPHYLLUM',
        'DRABA VERNA',
        'DRACUNCULUS VULGARIS',
        'DROSERA ROTUNDIFOLIA',
        'DRYAS OCTOPETALA',
        'DRYOPTERIS FILIX-MAS',
        'ECBALLIUM ELATERIUM',
        'ECHINOPHORA SPINOSA',
        'ECHINOPS RITRO',
        'ECHIUM VULGARE',
        'ELAEAGNUS ANGUSTIFOLIA',
        'EPHEDRA DISTACHYA',
        'EPILOBIUM ANGUSTIFOLIUM',
        'EPILOBIUM DODONAEI',
        'EPILOBIUM HIRSUTUM',
        'EPILOBIUM TETRAGONUM',
        'EPIPACTIS ATRORUBENS',
        'EPIPACTIS HELLEBORINE',
        'EPIPACTIS PALUSTRIS',
        'EQUISETUM TELMATEIA',
        'ERANTHIS HYEMALIS',
        'ERICA ARBOREA',
        'ERICA CINEREA',
        'ERICA TETRALIX',
        'ERICA VAGANS',
        'ERIGERON ANNUUS',
        'ERIGERON CANADENSIS',
        'ERIGERON KARVINSKIANUS',
        'ERIGERON SUMATRENSIS',
        'ERINUS ALPINUS',
        'ERIOBOTRYA JAPONICA',
        'ERIOPHORUM ANGUSTIFOLIUM',
        'ERODIUM CICONIUM',
        'ERODIUM CICUTARIUM',
        'ERODIUM FOETIDUM',
        'ERODIUM MALACOIDES',
        'ERYNGIUM BOURGATII',
        'ERYNGIUM CAMPESTRE',
        'ERYNGIUM MARITIMUM',
        'ERYNGIUM SPINALBA',
        'ERYSIMUM CHEIRI',
        'ERYTHRONIUM DENS-CANIS',
        'ESCHSCHOLZIA CALIFORNICA',
        'EUONYMUS EUROPAEUS',
        'EUONYMUS LATIFOLIUS',
        'EUPATORIUM CANNABINUM',
        'EUPHORBIA AMYGDALOIDES',
        'EUPHORBIA CHARACIAS',
        'EUPHORBIA CYPARISSIAS',
        'EUPHORBIA DENDROIDES',
        'EUPHORBIA FLAVICOMA',
        'EUPHORBIA HELIOSCOPIA',
        'EUPHORBIA LATHYRIS',
        'EUPHORBIA NICAEENSIS',
        'EUPHORBIA PARALIAS',
        'EUPHORBIA PEPLIS',
        'EUPHORBIA PEPLUS',
        'EUPHORBIA SEGETALIS',
        'EUPHORBIA SEGUIERIANA',
        'EUPHORBIA SERRATA',
        'EUPHORBIA SPINOSA',
        'FAGUS SYLVATICA',
        'FATSIA JAPONICA',
        'FEIJOA SELLOWIANA',
        'FERULA COMMUNIS',
        'FICARIA VERNA',
        'FICUS CARICA',
        'FILIPENDULA ULMARIA',
        'FILIPENDULA VULGARIS',
        'FOENICULUM VULGARE',
        'FRAGARIA VESCA',
        'FRANGULA DODONEI',
        'FRAXINUS ANGUSTIFOLIA',
        'FRAXINUS EXCELSIOR',
        'FRAXINUS ORNUS',
        'FRITILLARIA MELEAGRIS',
        'FRITILLARIA PYRENAICA',
        'FUMARIA CAPREOLATA',
        'FUMARIA OFFICINALIS',
        'GAGEA BOHEMICA',
        'GAGEA GRANATELLI',
        'GALACTITES TOMENTOSUS',
        'GALANTHUS NIVALIS',
        'GALEOPSIS TETRAHIT',
        'GALINSOGA QUADRIRADIATA',
        'GALIUM APARINE',
        'GALIUM ODORATUM',
        'GALIUM VERUM',
        'GENISTA HISPANICA',
        'GENISTA PILOSA',
        'GENISTA SAGITTALIS',
        'GENISTA SCORPIUS',
        'GENISTA TINCTORIA',
        'GENTIANA ACAULIS',
        'GENTIANA ALPINA',
        'GENTIANA BURSERI',
        'GENTIANA CRUCIATA',
        'GENTIANA LUTEA',
        'GENTIANA NIVALIS',
        'GENTIANA PNEUMONANTHE',
        'GENTIANA PURPUREA',
        'GENTIANA PYRENAICA',
        'GENTIANA VERNA',
        'GENTIANELLA CAMPESTRIS',
        'GENTIANOPSIS CILIATA',
        'GERANIUM COLUMBINUM',
        'GERANIUM DISSECTUM',
        'GERANIUM LUCIDUM',
        'GERANIUM MOLLE',
        'GERANIUM NODOSUM',
        'GERANIUM PHAEUM',
        'GERANIUM PRATENSE',
        'GERANIUM PUSILLUM',
        'GERANIUM PYRENAICUM',
        'GERANIUM ROBERTIANUM',
        'GERANIUM ROTUNDIFOLIUM',
        'GERANIUM SANGUINEUM',
        'GERANIUM SYLVATICUM',
        'GEUM MONTANUM',
        'GEUM REPTANS',
        'GEUM RIVALE',
        'GEUM URBANUM',
        'GINKGO BILOBA',
        'GLADIOLUS ITALICUS',
        'GLAUCIUM FLAVUM',
        'GLECHOMA HEDERACEA',
        'GLEDITSIA TRIACANTHOS',
        'GLOBULARIA ALYPUM',
        'GLOBULARIA BISNAGARICA',
        'GLOBULARIA REPENS',
        'GYMNADENIA CONOPSEA',
        'GYMNADENIA NIGRA',
        'HEDERA HELIX',
        'HELIANTHEMUM APENNINUM',
        'HELIANTHEMUM NUMMULARIUM',
        'HELIANTHUS ANNUUS',
        'HELICHRYSUM STOECHAS',
        'HELIOTROPIUM EUROPAEUM',
        'HELLEBORUS FOETIDUS',
        'HELLEBORUS VIRIDIS',
        'HELMINTHOTHECA ECHIOIDES',
        'HEMEROCALLIS FULVA',
        'HERACLEUM PYRENAICUM',
        'HERACLEUM SPHONDYLIUM',
        'HESPERIS MATRONALIS',
        'HIBISCUS ROSA-SINENSIS',
        'HIBISCUS SYRIACUS',
        'HIMANTOGLOSSUM HIRCINUM',
        'HIMANTOGLOSSUM ROBERTIANUM',
        'HIPPOCREPIS COMOSA',
        'HIPPOCREPIS EMERUS',
        'HOLCUS LANATUS',
        'HOMOGYNE ALPINA',
        'HONCKENYA PEPLOIDES',
        'HORMATHOPHYLLA SPINOSA',
        'HUMULUS LUPULUS',
        'HYACINTHOIDES NON-SCRIPTA',
        'HYDRANGEA MACROPHYLLA',
        'HYLOTELEPHIUM TELEPHIUM',
        'HYOSCYAMUS ALBUS',
        'HYOSERIS RADIATA',
        'HYPARRHENIA HIRTA',
        'HYPERICUM ANDROSAEMUM',
        'HYPERICUM HIRSUTUM',
        'HYPERICUM PERFORATUM',
        'HYPERICUM RICHERI',
        'HYPOCHAERIS RADICATA',
        'ILEX AQUIFOLIUM',
        'IMPATIENS BALFOURI',
        'IMPATIENS GLANDULIFERA',
        'IMPERATORIA OSTRUTHIUM',
        'INULA CONYZA',
        'IRIS FOETIDISSIMA',
        'IRIS LUTESCENS',
        'IRIS PSEUDACORUS',
        'ISATIS TINCTORIA',
        'JACOBAEA ADONIDIFOLIA',
        'JACOBAEA ERUCIFOLIA',
        'JACOBAEA MARITIMA',
        'JACOBAEA VULGARIS',
        'JASIONE MONTANA',
        'JASMINUM FRUTICANS',
        'JUGLANS NIGRA',
        'JUGLANS REGIA',
        'JUNCUS BULBOSUS',
        'JUNCUS EFFUSUS',
        'JUNCUS GERARDI',
        'JUNIPERUS COMMUNIS',
        'JUNIPERUS OXYCEDRUS',
        'JUNIPERUS PHOENICEA',
        'JUNIPERUS SABINA',
        'KERRIA JAPONICA',
        'KICKXIA SPURIA',
        'KNAUTIA ARVENSIS',
        'KNAUTIA MAXIMA',
        'KOELREUTERIA PANICULATA',
        'LABURNUM ANAGYROIDES',
        'LACTUCA ALPINA',
        'LACTUCA MURALIS',
        'LACTUCA PERENNIS',
        'LACTUCA PLUMIERI',
        'LACTUCA SERRIOLA',
        'LACTUCA VIMINEA',
        'LAGURUS OVATUS',
        'LAMIUM ALBUM',
        'LAMIUM AMPLEXICAULE',
        'LAMIUM GALEOBDOLON',
        'LAMIUM MACULATUM',
        'LAMIUM PURPUREUM',
        'LANTANA CAMARA',
        'LAPSANA COMMUNIS',
        'LARIX DECIDUA',
        'LATHRAEA CLANDESTINA',
        'LATHYRUS CICERA',
        'LATHYRUS LATIFOLIUS',
        'LATHYRUS PRATENSIS',
        'LATHYRUS SYLVESTRIS',
        'LAURUS NOBILIS',
        'LAVANDULA STOECHAS',
        'LEGOUSIA SPECULUM-VENERIS',
        'LEONTODON HISPIDUS',
        'LEONTOPODIUM NIVALE',
        'LEPIDIUM DRABA',
        'LEUCANTHEMOPSIS ALPINA',
        'LEUCANTHEMUM VULGARE',
        'LIGUSTRUM VULGARE',
        'LILIUM MARTAGON',
        'LILIUM PYRENAICUM',
        'LIMODORUM ABORTIVUM',
        'LIMONIASTRUM MONOPETALUM',
        'LIMONIUM NARBONENSE',
        'LIMONIUM VULGARE',
        'LINARIA ALPINA',
        'LINARIA REPENS',
        'LINARIA SUPINA',
        'LINARIA VULGARIS',
        'LINUM CAMPANULATUM',
        'LINUM NARBONENSE',
        'LINUM SUFFRUTICOSUM',
        'LINUM USITATISSIMUM',
        'LIPPIA TRIPHYLLA',
        'LIQUIDAMBAR STYRACIFLUA',
        'LIRIODENDRON TULIPIFERA',
        'LITHODORA FRUTICOSA',
        'LITHOSPERMUM OFFICINALE',
        'LOBULARIA MARITIMA',
        'LONCOMELOS PYRENAICUS',
        'LONICERA ALPIGENA',
        'LONICERA ETRUSCA',
        'LONICERA IMPLEXA',
        'LONICERA PERICLYMENUM',
        'LONICERA XYLOSTEUM',
        'LOTUS CORNICULATUS',
        'LOTUS EDULIS',
        'LOTUS MARITIMUS',
        'LUNARIA ANNUA',
        'LUPINUS ANGUSTIFOLIUS',
        'LUZULA CAMPESTRIS',
        'LYCHNIS CORONARIA',
        'LYCHNIS FLOS-CUCULI',
        'LYCOPSIS ARVENSIS',
        'LYCOPUS EUROPAEUS',
        'LYSIMACHIA ARVENSIS',
        'LYSIMACHIA NEMORUM',
        'LYSIMACHIA VULGARIS',
        'LYTHRUM SALICARIA',
        'MAGNOLIA GRANDIFLORA',
        'MALUS DOMESTICA',
        'MALUS SYLVESTRIS',
        'MALVA ARBOREA',
        'MALVA MOSCHATA',
        'MALVA NEGLECTA',
        'MALVA SETIGERA',
        'MALVA SYLVESTRIS',
        'MATRICARIA CHAMOMILLA',
        'MATTHIOLA INCANA',
        'MATTHIOLA SINUATA',
        'MAYTENUS CANARIENSIS',
        'MECONOPSIS CAMBRICA',
        'MEDICAGO ARBOREA',
        'MEDICAGO LUPULINA',
        'MEDICAGO SATIVA',
        'MELAMPYRUM PRATENSE',
        'MELIA AZEDARACH',
        'MELILOTUS ALBUS',
        'MELISSA OFFICINALIS',
        'MELITTIS MELISSOPHYLLUM',
        'MENTHA AQUATICA',
        'MENTHA ARVENSIS',
        'MENTHA LONGIFOLIA',
        'MENTHA SPICATA',
        'MENTHA SUAVEOLENS',
        'MERCURIALIS ANNUA',
        'MERCURIALIS PERENNIS',
        'MICROTHLASPI PERFOLIATUM',
        'MIRABILIS JALAPA',
        'MISOPATES ORONTIUM',
        'MONOTROPA HYPOPITYS',
        'MORUS ALBA',
        'MORUS KAGAYAMAE',
        'MUSCARI COMOSUM',
        'MUSCARI NEGLECTUM',
        'MYOSOTIS ALPESTRIS',
        'MYOSOTIS ARVENSIS',
        'MYOSOTIS SCORPIOIDES',
        'MYOSOTON AQUATICUM',
        'MYRTUS COMMUNIS',
        'NARCISSUS ASSOANUS',
        'NARCISSUS DUBIUS',
        'NARCISSUS PSEUDONARCISSUS',
        'NARCISSUS TAZETTA',
        'NASTURTIUM OFFICINALE',
        'NEOTINEA USTULATA',
        'NEOTTIA NIDUS-AVIS',
        'NEOTTIA OVATA',
        'NERIUM OLEANDER',
        'NIGELLA DAMASCENA',
        'ODONTITES LUTEUS',
        'ODONTITES VERNUS',
        'OENANTHE CROCATA',
        'OENOTHERA BIENNIS',
        'OENOTHERA GLAZIOVIANA',
        'OLEA EUROPAEA',
        'ONOBRYCHIS VICIIFOLIA',
        'ONONIS MINUTISSIMA',
        'ONONIS NATRIX',
        'ONONIS RECLINATA',
        'ONONIS SPINOSA',
        'ONOPORDUM ACANTHIUM',
        'OPHRYS APIFERA',
        'OPHRYS ARACHNITIFORMIS',
        'OPHRYS ARANIFERA',
        'OPHRYS BERTOLONII',
        'OPHRYS FUCIFLORA',
        'OPHRYS INSECTIFERA',
        'OPHRYS LUPERCALIS',
        'OPHRYS LUTEA',
        'OPHRYS PASSIONIS',
        'OPHRYS SCOLOPAX',
        'OPHRYS SPECULUM',
        'OPHRYS VIRESCENS',
        'OPUNTIA FICUS-INDICA',
        'ORCHIS ANTHROPOPHORA',
        'ORCHIS MASCULA',
        'ORCHIS PROVINCIALIS',
        'ORCHIS PURPUREA',
        'ORCHIS SIMIA',
        'ORIGANUM VULGARE',
        'ORNITHOGALUM UMBELLATUM',
        'OROBANCHE AMETHYSTEA',
        'OROBANCHE CARYOPHYLLACEA',
        'OROBANCHE GRACILIS',
        'OROBANCHE HEDERAE',
        'OROBANCHE MINOR',
        'OROBANCHE RAPUM-GENISTAE',
        'OSMUNDA REGALIS',
        'OSTRYA CARPINIFOLIA',
        'OXALIS ARTICULATA',
        'OXALIS CORNICULATA',
        'PALIURUS SPINA-CHRISTI',
        'PALLENIS SPINOSA',
        'PANCRATIUM MARITIMUM',
        'PAPAVER ALPINUM',
        'PAPAVER RHOEAS',
        'PAPAVER SOMNIFERUM',
        'PARDOGLOSSUM CHEIRIFOLIUM',
        'PARIETARIA JUDAICA',
        'PARIS QUADRIFOLIA',
        'PARNASSIA PALUSTRIS',
        'PARTHENOCISSUS QUINQUEFOLIA',
        'PARTHENOCISSUS TRICUSPIDATA',
        'PASSIFLORA CAERULEA',
        'PASTINACA SATIVA',
        'PAULOWNIA TOMENTOSA',
        'PEROVSKIA ATRIPLICIFOLIA',
        'PERSICARIA MACULOSA',
        'PETASITES PYRENAICUS',
        'PHACELIA TANACETIFOLIA',
        'PHILADELPHUS CORONARIUS',
        'PHILLYREA ANGUSTIFOLIA',
        'PHILLYREA MEDIA',
        'PHLEUM PRATENSE',
        'PHLOMIS FRUTICOSA',
        'PHOTINIA SERRULATA',
        'PHYTEUMA HEMISPHAERICUM',
        'PHYTEUMA SPICATUM',
        'PHYTOLACCA AMERICANA',
        'PICRIS HIERACIOIDES',
        'PILOSELLA AURANTIACA',
        'PILOSELLA LACTUCELLA',
        'PILOSELLA OFFICINARUM',
        'PINGUICULA GRANDIFLORA',
        'PINUS BRUTIA',
        'PINUS CEMBRA',
        'PINUS HALEPENSIS',
        'PINUS MUGO',
        'PINUS NIGRA',
        'PINUS PINASTER',
        'PINUS PINEA',
        'PINUS SYLVESTRIS',
        'PISTACIA LENTISCUS',
        'PISTACIA TEREBINTHUS',
        'PITTOSPORUM TENUIFOLIUM',
        'PITTOSPORUM TOBIRA',
        'PLANTAGO CORONOPUS',
        'PLANTAGO LAGOPUS',
        'PLANTAGO LANCEOLATA',
        'PLANTAGO MAJOR',
        'PLANTAGO MARITIMA',
        'PLANTAGO MEDIA',
        'PLATANTHERA BIFOLIA',
        'PLATANTHERA CHLORANTHA',
        'PLATANUS ORIENTALIS',
        'PLATANUS X',
        'POA ANNUA',
        'POLYGALA VULGARIS',
        'POLYGONATUM MULTIFLORUM',
        'POLYGONATUM ODORATUM',
        'POLYPODIUM VULGARE',
        'POLYSTICHUM SETIFERUM',
        'POPULUS ALBA',
        'POPULUS NIGRA',
        'POPULUS TREMULA',
        'POPULUS TRICHOCARPA',
        'PORTULACA OLERACEA',
        'POTENTILLA ERECTA',
        'POTENTILLA INDICA',
        'POTENTILLA RECTA',
        'POTENTILLA REPTANS',
        'POTENTILLA STERILIS',
        'POTENTILLA TABERNAEMONTANI',
        'POTERIUM SANGUISORBA',
        'PRENANTHES PURPUREA',
        'PRIMULA ELATIOR',
        'PRIMULA VERIS',
        'PRIMULA VULGARIS',
        'PROSPERO AUTUMNALE',
        'PRUNELLA GRANDIFLORA',
        'PRUNELLA HASTIFOLIA',
        'PRUNELLA LACINIATA',
        'PRUNELLA VULGARIS',
        'PRUNUS ARMENIACA',
        'PRUNUS AVIUM',
        'PRUNUS CERASIFERA',
        'PRUNUS DULCIS',
        'PRUNUS LAUROCERASUS',
        'PRUNUS MAHALEB',
        'PRUNUS PADUS',
        'PRUNUS SEROTINA',
        'PRUNUS SERRULATA',
        'PRUNUS SPINOSA',
        'PSEUDORCHIS ALBIDA',
        'PSEUDOTURRITIS TURRITA',
        'PTERIDIUM AQUILINUM',
        'PTEROCARYA FRAXINIFOLIA',
        'PULICARIA DYSENTERICA',
        'PUNICA GRANATUM',
        'PYRACANTHA COCCINEA',
        'PYRUS COMMUNIS',
        'QUERCUS CERRIS',
        'QUERCUS COCCIFERA',
        'QUERCUS ILEX',
        'QUERCUS PALUSTRIS',
        'QUERCUS PETRAEA',
        'QUERCUS PUBESCENS',
        'QUERCUS ROBUR',
        'QUERCUS RUBRA',
        'QUERCUS SUBER',
        'RANUNCULUS ACONITIFOLIUS',
        'RANUNCULUS ACRIS',
        'RANUNCULUS BULBOSUS',
        'RANUNCULUS FLAMMULA',
        'RANUNCULUS GRAMINEUS',
        'RANUNCULUS PALUDOSUS',
        'RANUNCULUS PARVIFLORUS',
        'RANUNCULUS PELTATUS',
        'RANUNCULUS PLATANIFOLIUS',
        'RANUNCULUS REPENS',
        'RANUNCULUS SCELERATUS',
        'RANUNCULUS TRICHOPHYLLUS',
        'RAPHANUS RAPHANISTRUM',
        'RESEDA LUTEA',
        'RESEDA LUTEOLA',
        'RESEDA PHYTEUMA',
        'REYNOUTRIA JAPONICA',
        'RHAMNUS ALATERNUS',
        'RHAMNUS ALPINA',
        'RHAMNUS CATHARTICA',
        'RHAMNUS PUMILA',
        'RHAPONTICUM CONIFERUM',
        'RHINANTHUS ALECTOROLOPHUS',
        'RHINANTHUS MINOR',
        'RHODODENDRON FERRUGINEUM',
        'RHUS CORIARIA',
        'RHUS TYPHINA',
        'RIBES RUBRUM',
        'ROBINIA PSEUDOACACIA',
        'ROSA AGRESTIS',
        'ROSA CANINA',
        'ROSA PENDULINA',
        'ROSA SPINOSISSIMA',
        'ROSMARINUS OFFICINALIS',
        'RUBIA TINCTORUM',
        'RUBUS FRUTICOSUS',
        'RUBUS IDAEUS',
        'RUBUS PEDATIFOLIUS',
        'RUBUS ULMIFOLIUS',
        'RUMEX ACETOSELLA',
        'RUMEX CRISPUS',
        'RUMEX OBTUSIFOLIUS',
        'RUSCUS ACULEATUS',
        'RUTA MONTANA',
        'SALIX ALBA',
        'SALIX BABYLONICA',
        'SALIX CAPREA',
        'SALIX CINEREA',
        'SALIX FRAGILIS',
        'SALIX HERBACEA',
        'SALVIA OFFICINALIS',
        'SALVIA PRATENSIS',
        'SALVIA VERBENACA',
        'SAMBUCUS EBULUS',
        'SAMBUCUS NIGRA',
        'SAMBUCUS RACEMOSA',
        'SAPONARIA OCYMOIDES',
        'SAPONARIA OFFICINALIS',
        'SATUREJA MONTANA',
        'SAXIFRAGA AIZOIDES',
        'SAXIFRAGA GRANULATA',
        'SAXIFRAGA MEDIA',
        'SAXIFRAGA MOSCHATA',
        'SAXIFRAGA PANICULATA',
        'SAXIFRAGA TRIDACTYLITES',
        'SCABIOSA ATROPURPUREA',
        'SCABIOSA COLUMBARIA',
        'SCILLA LUCILIAE',
        'SCOLYMUS HISPANICUS',
        'SCORZONEROIDES PYRENAICA',
        'SCROPHULARIA AURICULATA',
        'SCROPHULARIA NODOSA',
        'SCUTELLARIA GALERICULATA',
        'SEDUM ACRE',
        'SEDUM ALBUM',
        'SEDUM DASYPHYLLUM',
        'SEDUM RUPESTRE',
        'SEDUM SEDIFORME',
        'SEMPERVIVUM ARACHNOIDEUM',
        'SEMPERVIVUM MONTANUM',
        'SEMPERVIVUM TECTORUM',
        'SENECIO DORONICUM',
        'SENECIO INAEQUIDENS',
        'SENECIO OVATUS',
        'SENECIO VULGARIS',
        'SERAPIAS LINGUA',
        'SERAPIAS VOMERACEA',
        'SHERARDIA ARVENSIS',
        'SIDERITIS ROMANA',
        'SILENE ACAULIS',
        'SILENE BACCIFERA',
        'SILENE CONICA',
        'SILENE DIOICA',
        'SILENE GALLICA',
        'SILENE ITALICA',
        'SILENE LATIFOLIA',
        'SILENE NUTANS',
        'SILENE UNIFLORA',
        'SILENE VULGARIS',
        'SILYBUM MARIANUM',
        'SINAPIS ARVENSIS',
        'SISYMBRIUM IRIO',
        'SISYMBRIUM OFFICINALE',
        'SMILAX ASPERA',
        'SMYRNIUM OLUSATRUM',
        'SOLANUM DULCAMARA',
        'SOLANUM NIGRUM',
        'SOLDANELLA ALPINA',
        'SOLIDAGO VIRGAUREA',
        'SONCHUS ASPER',
        'SONCHUS TENERRIMUS',
        'SOPHORA JAPONICA',
        'SORBUS ARIA',
        'SORBUS AUCUPARIA',
        'SORBUS DOMESTICA',
        'SORBUS INTERMEDIA',
        'SORBUS TORMINALIS',
        'SPARTIUM JUNCEUM',
        'SPERGULA ARVENSIS',
        'SPERGULA MEDIA',
        'SPIRANTHES SPIRALIS',
        'STACHYS RECTA',
        'STACHYS SYLVATICA',
        'STAEHELINA DUBIA',
        'STELLARIA HOLOSTEA',
        'STELLARIA MEDIA',
        'SUCCISA PRATENSIS',
        'SYMPHYTUM OFFICINALE',
        'SYMPHYTUM TUBEROSUM',
        'SYRINGA VULGARIS',
        'TANACETUM VULGARE',
        'TARAXACUM CAMPYLODES',
        'TARAXACUM OFFICINALE',
        'TAXUS BACCATA',
        'TEUCRIUM CHAMAEDRYS',
        'TEUCRIUM FLAVUM',
        'TEUCRIUM FRUTICANS',
        'TEUCRIUM MONTANUM',
        'TEUCRIUM SCORODONIA',
        'THALICTRUM AQUILEGIIFOLIUM',
        'THYMUS SERPYLLUM',
        'THYMUS VULGARIS',
        'TILIA CORDATA',
        'TILIA DASYSTYLA',
        'TILIA PLATYPHYLLOS',
        'TORDYLIUM APULUM',
        'TORDYLIUM MAXIMUM',
        'TORILIS ARVENSIS',
        'TOZZIA ALPINA',
        'TRACTEMA LILIO-HYACINTHUS',
        'TRACTEMA VERNA',
        'TRAGOPOGON PORRIFOLIUS',
        'TRAGOPOGON PRATENSIS',
        'TRIBULUS TERRESTRIS',
        'TRIFOLIUM ALPINUM',
        'TRIFOLIUM CAMPESTRE',
        'TRIFOLIUM CHERLERI',
        'TRIFOLIUM INCARNATUM',
        'TRIFOLIUM PRATENSE',
        'TRIFOLIUM REPENS',
        'TRIFOLIUM RESUPINATUM',
        'TRIFOLIUM SCABRUM',
        'TRIFOLIUM STELLATUM',
        'TRIFOLIUM SUBTERRANEUM',
        'TRIPLEUROSPERMUM INODORUM',
        'TRIPODION TETRAPHYLLUM',
        'TRIPOLIUM PANNONICUM',
        'TROLLIUS EUROPAEUS',
        'TUBERARIA GUTTATA',
        'TULIPA SYLVESTRIS',
        'TUSSILAGO FARFARA',
        'ULEX EUROPAEUS',
        'ULEX GALLII',
        'ULMUS MINOR',
        'UMBILICUS RUPESTRIS',
        'UROSPERMUM DALECHAMPII',
        'URTICA DIOICA',
        'VACCINIUM MYRTILLUS',
        'VACCINIUM VITIS-IDAEA',
        'VALERIANA CELTICA',
        'VALERIANA OFFICINALIS',
        'VERATRUM ALBUM',
        'VERBASCUM BLATTARIA',
        'VERBASCUM BOERHAVII',
        'VERBASCUM LYCHNITIS',
        'VERBASCUM NIGRUM',
        'VERBASCUM PULVERULENTUM',
        'VERBASCUM SINUATUM',
        'VERBASCUM THAPSUS',
        'VERBENA OFFICINALIS',
        'VERONICA ANAGALLIS-AQUATICA',
        'VERONICA ARVENSIS',
        'VERONICA BECCABUNGA',
        'VERONICA CHAMAEDRYS',
        'VERONICA CYMBALARIA',
        'VERONICA HEDERIFOLIA',
        'VERONICA OFFICINALIS',
        'VERONICA PERSICA',
        'VERONICA SERPYLLIFOLIA',
        'VIBURNUM LANTANA',
        'VIBURNUM OPULUS',
        'VIBURNUM RHYTIDOPHYLLUM',
        'VIBURNUM TINUS',
        'VICIA CRACCA',
        'VICIA HIRSUTA',
        'VICIA HYBRIDA',
        'VICIA PANNONICA',
        'VICIA SATIVA',
        'VICIA SEPIUM',
        'VINCA MAJOR',
        'VINCA MINOR',
        'VINCETOXICUM HIRUNDINARIA',
        'VINCETOXICUM NIGRUM',
        'VIOLA ALBA',
        'VIOLA ARVENSIS',
        'VIOLA BIFLORA',
        'VIOLA CALCARATA',
        'VIOLA CORNUTA',
        'VIOLA LUTEA',
        'VIOLA ODORATA',
        'VIOLA RIVINIANA',
        'VIOLA TRICOLOR',
        'VISCUM ALBUM',
        'VITEX AGNUS-CASTUS',
        'VITIS VINIFERA',
        'WISTERIA SINENSIS'
    ]

    #141 common species
    CR_ASU_COMMON_SPECIES_LIST = [
        'Alvaradoa amorphoides',
        'Ambrosia peruviana',
        'Anacardium excelsum',
        'Apeiba tibourbou',
        'Aphelandra scabra',
        'Ardisia compressa',
        'Ardisia revoluta',
        'Asclepias curassavica',
        'Astronium graveolens',
        'Bauhinia ungulata',
        'Begonia semiovata',
        'Bixa orellana',
        'Brosimum alicastrum',
        'Buddleja americana',
        'Byrsonima crassifolia',
        'Cajanus cajan',
        'Calea urticifolia',
        'Calophyllum brasiliense',
        'Calycophyllum candidissimum',
        'Carica papaya',
        'Cecropia peltata',
        'Cestrum tomentosum',
        'Chiococca alba',
        'Chrysobalanus icaco',
        'Clibadium surinamense',
        'Clusia rosea',
        'Cnidoscolus aconitifolius',
        'Coccoloba acapulcensis',
        'Coccoloba caracasana',
        'Coccoloba uvifera',
        'Cochlospermum vitifolium',
        'Conostegia xalapensis',
        'Cordia alliodora',
        'Cordia dentata',
        'Crescentia alata',
        'Crescentia cujete',
        'Croton draco',
        'Croton niveus',
        'Croton schiedeanus',
        'Dendropanax arboreus',
        'Ehretia latifolia',
        'Eugenia oerstediana',
        'Eugenia uniflora',
        'Euphorbia cotinifolia',
        'Ficus benjamina',
        'Ficus citrifolia',
        'Ficus costaricana',
        'Ficus cotinifolia',
        'Ficus insipida',
        'Ficus maxima',
        'Ficus obtusifolia',
        'Galphimia gracilis',
        'Genipa americana',
        'Gliricidia sepium',
        'Gossypium hirsutum',
        'Guazuma ulmifolia',
        'Hamelia patens',
        'Heliocarpus appendiculatus',
        'Hibiscus rosa-sinensis',
        'Hura crepitans',
        'Hymenaea courbaril',
        'Hyptis pectinata',
        'Impatiens balsamina',
        'Ixora coccinea',
        'Jatropha curcas',
        'Jatropha gossypiifolia',
        'Justicia aurea',
        'Lantana camara',
        'Luehea speciosa',
        'Maclura tinctoria',
        'Malpighia glabra',
        'Malvaviscus arboreus',
        'Mangifera indica',
        'Manihot esculenta',
        'Mauria heterophylla',
        'Megaskepasma erythrochlamys',
        'Melaleuca quinquenervia',
        'Miconia argentea',
        'Montanoa hibiscifolia',
        'Morus alba',
        'Muntingia calabura',
        'Myrcia splendens',
        'Myriocarpa longipes',
        'Nerium oleander',
        'Neurolaena lobata',
        'Nicotiana tabacum',
        'Ochroma pyramidale',
        'Pereskia grandifolia',
        'Persea americana',
        'Petiveria alliacea',
        'Phoradendron quadrangulare',
        'Picramnia antidesma',
        'Pimenta dioica',
        'Piper aduncum',
        'Piper auritum',
        'Piper tuberculatum',
        'Piper umbellatum',
        'Platymiscium pinnatum',
        'Plumeria rubra',
        'Posoqueria latifolia',
        'Pouteria campechiana',
        'Psidium friedrichsthalianum',
        'Psidium guajava',
        'Psidium sartorianum',
        'Psychotria horizontalis',
        'Psychotria pubescens',
        'Quercus corrugata',
        'Quercus salicifolia',
        'Randia aculeata',
        'Rivina humilis',
        'Samanea saman',
        'Sambucus mexicana',
        'Sapium glandulosum',
        'Schinus terebinthifolius',
        'Schoepfia schreberi',
        'Securidaca sylvestris',
        'Sideroxylon capiri',
        'Simarouba glauca',
        'Sloanea terniflora',
        'Solanum umbellatum',
        'Spondias purpurea',
        'Stemmadenia donnell-smithii',
        'Sterculia apetala',
        'Swietenia macrophylla',
        'Syzygium jambos',
        'Syzygium paniculatum',
        'Tabebuia impetiginosa',
        'Tabebuia ochracea',
        'Tabebuia rosea',
        'Talinum paniculatum',
        'Tecoma stans',
        'Terminalia amazonia',
        'Terminalia catappa',
        'Theobroma cacao',
        'Thevetia peruviana',
        'Thouinidium decandrum',
        'Tournefortia glabra',
        'Trichilia havanensis',
        'Ulmus mexicana',
        'Urera caracasana',
        'Vernonia patens'
    ]

    #159 common genuses
    CR_ASU_COMMON_GENUS_LIST = [
        'Aegiphila',
        'Allophylus',
        'Alvaradoa',
        'Ambrosia',
        'Amyris',
        'Anacardium',
        'Annona',
        'Apeiba',
        'Aphelandra',
        'Ardisia',
        'Aristolochia',
        'Artocarpus',
        'Asclepias',
        'Astronium',
        'Barleria',
        'Bauhinia',
        'Begonia',
        'Bixa',
        'Blakea',
        'Bougainvillea',
        'Brosimum',
        'Brunfelsia',
        'Buddleja',
        'Bunchosia',
        'Byrsonima',
        'Cajanus',
        'Calea',
        'Calophyllum',
        'Calycophyllum',
        'Carica',
        'Casearia',
        'Cecropia',
        'Cedrela',
        'Cestrum',
        'Chiococca',
        'Chrysobalanus',
        'Chrysophyllum',
        'Cinnamomum',
        'Citharexylum',
        'Clethra',
        'Clibadium',
        'Clusia',
        'Cnidoscolus',
        'Coccoloba',
        'Cochlospermum',
        'Colubrina',
        'Conostegia',
        'Cordia',
        'Crescentia',
        'Critonia',
        'Croton',
        'Cryptostegia',
        'Dalbergia',
        'Dendropanax',
        'Diphysa',
        'Duranta',
        'Ehretia',
        'Erythrina',
        'Eucalyptus',
        'Eugenia',
        'Euphorbia',
        'Ficus',
        'Galphimia',
        'Genipa',
        'Gliricidia',
        'Gossypium',
        'Guaiacum',
        'Guazuma',
        'Hamelia',
        'Hampea',
        'Heliocarpus',
        'Hibiscus',
        'Hura',
        'Hyeronima',
        'Hymenaea',
        'Hyptis',
        'Impatiens',
        'Ixora',
        'Jatropha',
        'Justicia',
        'Lafoensia',
        'Lantana',
        'Ligustrum',
        'Luehea',
        'Maclura',
        'Malpighia',
        'Malvaviscus',
        'Mangifera',
        'Manihot',
        'Manilkara',
        'Mauria',
        'Megaskepasma',
        'Melaleuca',
        'Miconia',
        'Montanoa',
        'Morinda',
        'Morus',
        'Muntingia',
        'Myrcia',
        'Myriocarpa',
        'Myrsine',
        'Nerium',
        'Neurolaena',
        'Nicotiana',
        'Ochroma',
        'Ocotea',
        'Pachira',
        'Passiflora',
        'Pereskia',
        'Persea',
        'Petiveria',
        'Phoradendron',
        'Picramnia',
        'Pimenta',
        'Piper',
        'Platymiscium',
        'Plumeria',
        'Posoqueria',
        'Pouteria',
        'Psidium',
        'Psychotria',
        'Quercus',
        'Randia',
        'Rivina',
        'Robinsonella',
        'Ruprechtia',
        'Samanea',
        'Sambucus',
        'Sapium',
        'Schinus',
        'Schoepfia',
        'Securidaca',
        'Sida',
        'Sideroxylon',
        'Simarouba',
        'Sloanea',
        'Solanum',
        'Spondias',
        'Stachytarpheta',
        'Stemmadenia',
        'Sterculia',
        'Struthanthus',
        'Swietenia',
        'Syzygium',
        'Tabebuia',
        'Tabernaemontana',
        'Talinum',
        'Tecoma',
        'Terminalia',
        'Theobroma',
        'Thevetia',
        'Thouinidium',
        'Tonduzia',
        'Tournefortia',
        'Trichilia',
        'Ulmus',
        'Urera',
        'Verbesina',
        'Vernonia'
    ]
