from enum import Enum

class TaxaFilters(Enum):

    #141 common species
    CR_ASU_COMMON_SPECIES_LIST = [
        'Alvaradoa amorphoides',
        'Ambrosia peruviana',
        'Anacardium excelsum',
        'Apeiba tibourbou',
        'Aphelandra scabra',
        'Ardisia compressa',
        'Ardisia revoluta',
        'Asclepias curassavica',
        'Astronium graveolens',
        'Bauhinia ungulata',
        'Begonia semiovata',
        'Bixa orellana',
        'Brosimum alicastrum',
        'Buddleja americana',
        'Byrsonima crassifolia',
        'Cajanus cajan',
        'Calea urticifolia',
        'Calophyllum brasiliense',
        'Calycophyllum candidissimum',
        'Carica papaya',
        'Cecropia peltata',
        'Cestrum tomentosum',
        'Chiococca alba',
        'Chrysobalanus icaco',
        'Clibadium surinamense',
        'Clusia rosea',
        'Cnidoscolus aconitifolius',
        'Coccoloba acapulcensis',
        'Coccoloba caracasana',
        'Coccoloba uvifera',
        'Cochlospermum vitifolium',
        'Conostegia xalapensis',
        'Cordia alliodora',
        'Cordia dentata',
        'Crescentia alata',
        'Crescentia cujete',
        'Croton draco',
        'Croton niveus',
        'Croton schiedeanus',
        'Dendropanax arboreus',
        'Ehretia latifolia',
        'Eugenia oerstediana',
        'Eugenia uniflora',
        'Euphorbia cotinifolia',
        'Ficus benjamina',
        'Ficus citrifolia',
        'Ficus costaricana',
        'Ficus cotinifolia',
        'Ficus insipida',
        'Ficus maxima',
        'Ficus obtusifolia',
        'Galphimia gracilis',
        'Genipa americana',
        'Gliricidia sepium',
        'Gossypium hirsutum',
        'Guazuma ulmifolia',
        'Hamelia patens',
        'Heliocarpus appendiculatus',
        'Hibiscus rosa-sinensis',
        'Hura crepitans',
        'Hymenaea courbaril',
        'Hyptis pectinata',
        'Impatiens balsamina',
        'Ixora coccinea',
        'Jatropha curcas',
        'Jatropha gossypiifolia',
        'Justicia aurea',
        'Lantana camara',
        'Luehea speciosa',
        'Maclura tinctoria',
        'Malpighia glabra',
        'Malvaviscus arboreus',
        'Mangifera indica',
        'Manihot esculenta',
        'Mauria heterophylla',
        'Megaskepasma erythrochlamys',
        'Melaleuca quinquenervia',
        'Miconia argentea',
        'Montanoa hibiscifolia',
        'Morus alba',
        'Muntingia calabura',
        'Myrcia splendens',
        'Myriocarpa longipes',
        'Nerium oleander',
        'Neurolaena lobata',
        'Nicotiana tabacum',
        'Ochroma pyramidale',
        'Pereskia grandifolia',
        'Persea americana',
        'Petiveria alliacea',
        'Phoradendron quadrangulare',
        'Picramnia antidesma',
        'Pimenta dioica',
        'Piper aduncum',
        'Piper auritum',
        'Piper tuberculatum',
        'Piper umbellatum',
        'Platymiscium pinnatum',
        'Plumeria rubra',
        'Posoqueria latifolia',
        'Pouteria campechiana',
        'Psidium friedrichsthalianum',
        'Psidium guajava',
        'Psidium sartorianum',
        'Psychotria horizontalis',
        'Psychotria pubescens',
        'Quercus corrugata',
        'Quercus salicifolia',
        'Randia aculeata',
        'Rivina humilis',
        'Samanea saman',
        'Sambucus mexicana',
        'Sapium glandulosum',
        'Schinus terebinthifolius',
        'Schoepfia schreberi',
        'Securidaca sylvestris',
        'Sideroxylon capiri',
        'Simarouba glauca',
        'Sloanea terniflora',
        'Solanum umbellatum',
        'Spondias purpurea',
        'Stemmadenia donnell-smithii',
        'Sterculia apetala',
        'Swietenia macrophylla',
        'Syzygium jambos',
        'Syzygium paniculatum',
        'Tabebuia impetiginosa',
        'Tabebuia ochracea',
        'Tabebuia rosea',
        'Talinum paniculatum',
        'Tecoma stans',
        'Terminalia amazonia',
        'Terminalia catappa',
        'Theobroma cacao',
        'Thevetia peruviana',
        'Thouinidium decandrum',
        'Tournefortia glabra',
        'Trichilia havanensis',
        'Ulmus mexicana',
        'Urera caracasana',
        'Vernonia patens'
    ]

    #159 common genuses
    CR_ASU_COMMON_GENUS_LIST = [
        'Aegiphila',
        'Allophylus',
        'Alvaradoa',
        'Ambrosia',
        'Amyris',
        'Anacardium',
        'Annona',
        'Apeiba',
        'Aphelandra',
        'Ardisia',
        'Aristolochia',
        'Artocarpus',
        'Asclepias',
        'Astronium',
        'Barleria',
        'Bauhinia',
        'Begonia',
        'Bixa',
        'Blakea',
        'Bougainvillea',
        'Brosimum',
        'Brunfelsia',
        'Buddleja',
        'Bunchosia',
        'Byrsonima',
        'Cajanus',
        'Calea',
        'Calophyllum',
        'Calycophyllum',
        'Carica',
        'Casearia',
        'Cecropia',
        'Cedrela',
        'Cestrum',
        'Chiococca',
        'Chrysobalanus',
        'Chrysophyllum',
        'Cinnamomum',
        'Citharexylum',
        'Clethra',
        'Clibadium',
        'Clusia',
        'Cnidoscolus',
        'Coccoloba',
        'Cochlospermum',
        'Colubrina',
        'Conostegia',
        'Cordia',
        'Crescentia',
        'Critonia',
        'Croton',
        'Cryptostegia',
        'Dalbergia',
        'Dendropanax',
        'Diphysa',
        'Duranta',
        'Ehretia',
        'Erythrina',
        'Eucalyptus',
        'Eugenia',
        'Euphorbia',
        'Ficus',
        'Galphimia',
        'Genipa',
        'Gliricidia',
        'Gossypium',
        'Guaiacum',
        'Guazuma',
        'Hamelia',
        'Hampea',
        'Heliocarpus',
        'Hibiscus',
        'Hura',
        'Hyeronima',
        'Hymenaea',
        'Hyptis',
        'Impatiens',
        'Ixora',
        'Jatropha',
        'Justicia',
        'Lafoensia',
        'Lantana',
        'Ligustrum',
        'Luehea',
        'Maclura',
        'Malpighia',
        'Malvaviscus',
        'Mangifera',
        'Manihot',
        'Manilkara',
        'Mauria',
        'Megaskepasma',
        'Melaleuca',
        'Miconia',
        'Montanoa',
        'Morinda',
        'Morus',
        'Muntingia',
        'Myrcia',
        'Myriocarpa',
        'Myrsine',
        'Nerium',
        'Neurolaena',
        'Nicotiana',
        'Ochroma',
        'Ocotea',
        'Pachira',
        'Passiflora',
        'Pereskia',
        'Persea',
        'Petiveria',
        'Phoradendron',
        'Picramnia',
        'Pimenta',
        'Piper',
        'Platymiscium',
        'Plumeria',
        'Posoqueria',
        'Pouteria',
        'Psidium',
        'Psychotria',
        'Quercus',
        'Randia',
        'Rivina',
        'Robinsonella',
        'Ruprechtia',
        'Samanea',
        'Sambucus',
        'Sapium',
        'Schinus',
        'Schoepfia',
        'Securidaca',
        'Sida',
        'Sideroxylon',
        'Simarouba',
        'Sloanea',
        'Solanum',
        'Spondias',
        'Stachytarpheta',
        'Stemmadenia',
        'Sterculia',
        'Struthanthus',
        'Swietenia',
        'Syzygium',
        'Tabebuia',
        'Tabernaemontana',
        'Talinum',
        'Tecoma',
        'Terminalia',
        'Theobroma',
        'Thevetia',
        'Thouinidium',
        'Tonduzia',
        'Tournefortia',
        'Trichilia',
        'Ulmus',
        'Urera',
        'Verbesina',
        'Vernonia'
    ]
